### ISSUE TITLE
Missing Gemfile or .bundle/ directory

### ISSUE THREAD

**Issue by hellosylvee** [mattrothenberg/persona-monitor#1]
I'm following the documentation, and I'm running an error in terminal. 

```
Sylvias-MacBook-Pro:workspace sylvialee$ bundle install
Could not locate Gemfile or .bundle/ directory
```

I've tried bundle install...but it still cannot locate Gemfile or .bundle/ directory. Any ideas to fix this?

**Comment by mattrothenberg** [comment]
@hellosylvee You'll need to `cd` into the repository that you cloned before you can run `bundle install`.

**Comment by hellosylvee** [comment]
Thanks! I ran into some other problems but I got that resolved.

**Comment by mattrothenberg** [comment]
@hellosylvee Can you open another issue for the other problem(s)?

**Comment by hellosylvee** [comment]
I ran into problems like not having correct rbenv version because I had rbenv version 2.3.0 set as default.
```
rbenv: version `2.3.1' is not installed (set by /Users/sylvialee/workspace/persona-monitor/.ruby-version)
```

After that, I needed a specific ruby version: 
```
pivotal-wifi-2-41:persona-monitor sylvialee$ bundle install
Fetching gem metadata from https://rubygems.org/............
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
activesupport-5.0.0.1 requires ruby version >= 2.2.2, which is incompatible with
the current version, ruby 2.1.3p242
```

After getting the right ruby version, I got a build error. I was missing an extension. 
```
An error occurred while installing rmagick (2.16.0), and Bundler cannot
continue.
Make sure that `gem install rmagick -v '2.16.0'` succeeds before bundling.
pivotal-wifi-2-41:persona-monitor sylvialee$ gem install rmagick -v '2.16.0'
Building native extensions.  This could take a while...
ERROR:  Error installing rmagick:
	ERROR: Failed to build gem native extension.
``` 

So I had to install imagemagick, and then it finally worked.

You could write edge cases in the document if other people run into same problems, but I think this is up to you! If you still want me to create issues for these problems, I can.

**Comment by mattrothenberg** [comment]
@hellosylvee This is so helpful, thank you!

I did a couple of things, accordingly.

- [ ] Removed the hard-coded Ruby version.
- [ ] Removed the dependency on Imagemagick entirely

Can you try deleting the repo from your machine, cloning it fresh (several commits have been made since you first pulled), and seeing if a simple `bundle install` does the trick?

**Comment by hellosylvee** [comment]
That worked @mattrothenberg! _so easy_.

**Comment by mattrothenberg** [comment]
@hellosylvee Music to my ears. Thank you very, very much for testing this out!
